# Generated by Django 2.2.6 on 2019-10-15 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_order_orderincart'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='S', max_length=10, verbose_name=(('S', 'Shirt'), ('SW', 'Sport wear'), ('OW', 'Outwear'))),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='label',
            field=models.CharField(default='P', max_length=10, verbose_name=(('P', 'primary'), ('S', 'secondary'), ('D', 'danger'))),
            preserve_default=False,
        ),
    ]
