# Generated by Django 2.2.6 on 2019-10-16 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='products',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='orderincart',
            old_name='products',
            new_name='product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.AddField(
            model_name='orderincart',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
