# Generated by Django 2.2.6 on 2019-11-18 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_order_coupon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='discount',
            new_name='amount',
        ),
    ]
